### ISSUE TITLE
Please add an option to b2

### ISSUE THREAD

**Issue by lyssdod** [cmake-js/boost-lib#3]
Hi,
I'm using Gentoo and custom boost build is picking default system configuration. Can you please add an option?

The solution is:
https://github.com/openwrt/packages/issues/1912

The full issue is: https://github.com/cmake-js/cmake-js/issues/58

**Comment by unbornchikken** [comment]
Does https://github.com/cmake-js/boost-lib/pull/6 resolve this?

**Comment by lyssdod** [comment]
No, it seems there's another place where `b2` gets called. I will open a PR
