### ISSUE TITLE
Embedding

### ISSUE THREAD

**Issue by lyssdod** [cmake-js/boost-lib#5]
Hi, I have to ship my addon as a precompiled binary (I think via `node-pre-gyp`). As far as I can see, boost-lib is compiled as static now, what are my steps to make the installation redistributable?

**Comment by unbornchikken** [comment]
I don't have any solution for this other than compiling on installation. I believe [supporting complex and expensive release workflows](https://github.com/mapbox/node-pre-gyp/blob/master/README.md) puts too much burden to module authors. That far more voluntary work than to expect module users to install compiler tools for their machines. It's just not worth it.

**Comment by lyssdod** [comment]
I've solved it by using `node-pre-gyp` with this shim `bindings.gyp':

```
{
  'targets': [
    {
      'target_name': 'cmakebuild',
      'target_type': 'none',
      'actions': [
        {
          'action_name': 'cmakejs',
          'inputs': ['./CMakeLists.txt'],
          'outputs': ['./build'],
          'action': [ 'npm', 'run', 'invokecmake' ]
        }
      ]
    }
  ]
}
```
