### ISSUE TITLE
OSX fail

### ISSUE THREAD

**Issue by lyssdod** [cmake-js/boost-lib#8]
Hi,

I'm trying to use boost-lib when building on OSX and it always picks up system boost headers:

https://travis-ci.org/lyssdod/node-libtorrent/jobs/161197112#L460

Despite it downloads 1.61, boost-lib reports 1.55, which is system version

**Comment by unbornchikken** [comment]
It has been fixed in master already, hasn't it?

**Comment by lyssdod** [comment]
Yes, thank you!
