### ISSUE TITLE
Using with travis

### ISSUE THREAD

**Issue by lyssdod** [cmake-js/boost-lib#9]
Hi,

I'm experiencing problems with building via Travis. Somehow boost-lib fails to set `Boost_FOUND` to `TRUE` and the whole build fails: https://travis-ci.org/lyssdod/node-libtorrent/jobs/161197106#L805

It doesn't happen locally, so I'm supposing it can be a environment-related issue

**Comment by unbornchikken** [comment]
Could you try it by inserting the following before this line: https://github.com/cmake-js/boost-lib/blob/master/cmake/BoostLib.cmake#L20

set(Boost_FOUND true)

**Comment by lyssdod** [comment]
No luck: https://travis-ci.org/lyssdod/node-libtorrent/jobs/161431705#L901
My patch: https://github.com/lyssdod/node-libtorrent/blob/master/boostlib.patch

**Comment by unbornchikken** [comment]
Well, I'm groping in the dark there. I believe find_package https://github.com/cmake-js/boost-lib/blob/master/cmake/BoostLib.cmake#L13 sets its values to cache as forced, and somehow it prevents our values propagate upper to the scope https://github.com/cmake-js/boost-lib/blob/master/cmake/BoostLib.cmake#L27. Cannot reproduce but this is the most obvious cause. Exactly like this SO issue: http://stackoverflow.com/questions/5006286/cmake-set-doesnt-work-on-same-variable-after-find-path-was-called

Anyway I believe changing https://github.com/cmake-js/boost-lib/blob/master/cmake/BoostLib.cmake#L27 to this code:

```cmake
set(Boost_FOUND ${Boost_FOUND} CACHE BOOLEAN "" FORCE)
set(Boost_INCLUDE_DIRS "${Boost_INCLUDE_DIRS}" CACHE STRING "" FORCE)
set(Boost_LIBRARIES "${Boost_LIBRARIES}" CACHE STRING "" FORCE)
```

Will resolve this issue. Could you try this at your side? Thanks.

**Comment by lyssdod** [comment]
@unbornchikken Unfortunately no luck also: https://travis-ci.org/lyssdod/node-libtorrent/jobs/161995682#L905

I've tried both the last variant and combined patch  — it still can not find boost

**Comment by unbornchikken** [comment]
Could you try with master? Gotta work that way.

**Comment by lyssdod** [comment]
Hi, I've tried but got another error: https://travis-ci.org/lyssdod/node-libtorrent/jobs/162096387#L1032
It looks like this is caused by Travis incorrectly setting environmental variables regarding new compiler. I'll try with Trusty image which (as they say) contains newer toolchain.

**Comment by lyssdod** [comment]
Unfortunately, using trusty didn't solve the problem: https://travis-ci.org/lyssdod/node-libtorrent/jobs/162097341#L902. How do you think, can it be connected to recent merge regarding setting `ToolSetVer` for boost?

**Comment by unbornchikken** [comment]
At least we have made progress. I'm thinking on the next step. We need a smarter toolchain detection for sure. Dunno how did we captured three part version for gcc though. That should be two part one.

**Comment by unbornchikken** [comment]
Next round in master. Please give it a try.

**Comment by lyssdod** [comment]
Yeah, the progress is definitely made :+1: 

For now it passed the build of boost itself, but stopped complaining about missing headers, though different on Linux and OSX:

https://travis-ci.org/lyssdod/node-libtorrent/jobs/162157466#L865
https://travis-ci.org/lyssdod/node-libtorrent/jobs/162157467#L843

I've opened an issue about that in libtorrent repo and they said it can be a boost installation problem:
https://github.com/arvidn/libtorrent/issues/1121

**Comment by unbornchikken** [comment]
Well, according to the logs, it does download and extracts functional headers, and include paths are set for sure, because there is only one include path for whole boost. Do you have home folder access for Travis? Or is this issue reproducible on Linux at your side? I don't have access to a dev machine until late evening to try out your stuff.

**Comment by lyssdod** [comment]
I've made a listing and header is there, at least for OSX: https://travis-ci.org/lyssdod/node-libtorrent/jobs/162172605#L1062

I can't reproduce it on my side (got it working on ubuntu 16.04 and gentoo), it happens only on Travis for some reason

**Comment by lyssdod** [comment]
Failed header for Linux is also in place: https://travis-ci.org/lyssdod/node-libtorrent/jobs/162185696#L1270

**Comment by lyssdod** [comment]
Hi, it turned out on the recent build it was my fault — I had to specify boost headers explicitly (somehow I thinked `cmake-js` will pick them up for me) and now everything is working. Thank you very much!

**Comment by unbornchikken** [comment]
Cool. I'll release master later today.
